name: API Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Start application
        run: |
          node src/server.js > server.log 2>&1 &
          echo "Servidor disparado em background..."

      - name: Wait for app
        run: |
          echo "Aguardando 60 segundos pela API..."
          npx wait-on http://localhost:3000/api-docs/ --timeout 60000
        
      - name: DEBUG - Show Server Logs on Failure
        if: failure()
        run: |
          echo "--- CONTEÚDO DO LOG DO SERVIDOR ---"
          cat server.log
          echo "--- FIM DO LOG ---"
      - name: Create Env File
        run: |
          mkdir -p API/postman/environments
          echo '${{ secrets.POSTMAN_ENV_JSON }}' > API/postman/environments/qa-commerce.postman_environment.json


      - name: Run API tests
        run: npm run test:api:login

      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-test-report
          path: reports/api/